### PR TITLE
More end to end tests

### PR DESCRIPTION
**Pull request by vsergiu93**
More end to end Dusk tests

### CODE REVIEW

**Comment by SerhiiCho** [comment]
I wish I could help man 😞 I've tried to run Dusk with Sail but no luck on mac m1

**Comment by brendt** [comment]
I run it locally on M2 (I guess M1 is the same). I just had to do the following

```
composer install
php artisan dusk:install
php artisan dusk
```

Worked fine

**Comment by vsergiu93** [comment]
> I wish I could help man 😞 I've tried to run Dusk with Sail but no luck on mac m1. The error was `Failed to connect to localhost port 9515 after 0 ms: Connection refused`

Hey @SerhiiCho, no worries, but it does seem a bit strange, next time you want to try,  can you make sure that in your `.env.dusk.local`  APP_URL is equal to `http://laravel.test`? It could be unrelated, but that localhost does seem a bit weird.
In any case my intention with sail was that everyone can easily jump in and contribute, but it seems I still have some work left to do on that part :).

**Comment by SerhiiCho** [comment]
> APP_URL is equal to `http://laravel.test`? It could be unrelated

My `APP_URL` is indeed equal to `http://laravel.test`.

> but it seems I still have some work left to do on that part :).

No worries, I think it's not working only in my case because I refuse to install Chrome on my laptop. Most people have Chrome installed and will not have any issues

**Comment by vsergiu93** [comment]
@SerhiiCho Hmm, I see, in theory it should work out of the box without you having to install chrome on your machine (not even sure you can install chrome on m1, and m2, I haven't found a build for arm), it should pull all that it needs and run all the services as docker containers. For example my setup is Windows 11 with wsl2, and in wsl2 I haven't installed chrome, and `sail dusk` still runs fine. 

One last thing,  in your  `.env` file do you have this line ` SELENIUM_IMAGE=seleniarm/standalone-chromium`?

In any case the whole sail dev experience is not really what I would like it to be, I'll have to see what I can improve there.

**Comment by SerhiiCho** [comment]
I didn't have `SELENIUM_IMAGE=seleniarm/standalone-chromium`, I had `SELENIUM_IMAGE=selenium/standalone-chrome` instead. I've changed it to what you said, and re-run everything, nothing changed. However, I've noticed that when I run `sail artisan dusk` and `sail dusk` I get different results. When I run `sail artisan dusk` I get 25 tests failed:

image

But when I run `sail dusk`, the execution is stuck:
image

But it creates a temporary `phpunit.dusk.xml` file that is removed when I cancel the `sail dusk` command.

**Comment by SerhiiCho** [comment]
Here are my containers:
```
~/www/open/rfc-vote (main) » sail up -d 
[+] Running 6/6
 ✔ Network rfc-vote_sail              Created                                                                                                 0.0s 
 ✔ Container rfc-vote-redis-1         Started                                                                                                 0.4s 
 ✔ Container rfc-vote-mysql-1         Started                                                                                                 0.4s 
 ✔ Container rfc-vote-selenium-1      Started                                                                                                 0.4s 
 ✔ Container rfc-vote-mailpit-1       Started                                                                                                 0.4s 
 ✔ Container rfc-vote-laravel.test-1  Started  
```

**Comment by SerhiiCho** [comment]
The funny thing is that when I restart by running `sail restart` and run `sail dusk`, I get a different result. I see my tests are executing in the terminal (without chrome window) and the result is 23 tests failed and 2 passes:
image

Here are the tests that pass:
1. test_if_no_argument_of_the_day_exists_we_do_not_render_title_and_argument
2. test_it_does_not_render_email_notifications_if_user_already_opted_for_email_notifications

**Comment by vsergiu93** [comment]
> I didn't have `SELENIUM_IMAGE=seleniarm/standalone-chromium`, I had `SELENIUM_IMAGE=selenium/standalone-chrome` instead. I've changed it to what you said, and re-run everything (including docker), nothing changed, same error. However, I've noticed that when I run `sail artisan dusk` and `sail dusk` I get different results. When I run `sail artisan dusk` I get 25 tests failed:
> But it creates a temporary `phpunit.dusk.xml` file that is removed when I cancel the `sail dusk` command.


Yeah, you need `seleniarm/standalone-chromium` image for m1, m2 macs, as I wrote in the docs, also yes dusk creates some files while the tests are running and then it reverts/deletes them. Please make sure you have run sail npm run build before running `sail dusk` or `sail npm run dev`

**Comment by SerhiiCho** [comment]
Running `sail npm run dev` didn't help

**Comment by vsergiu93** [comment]
I see, hmm, it's a bit hard to understand why is not working for you, as I don't have a m1 or m2 mac to try and setup the project and see what are the problems, it could be that something small is missing in .env files or something more complex going on.
For now I'm out of ideas, as to what else we can try, maybe another dev will give it a go soon and they will be able to complete the docs with what needs to be done for m1.m2 macs to get dusk running.

**Comment by SerhiiCho** [comment]
I've deleted the project image and ran `sail up`. It started building containers and error out with this message: `36.85 E: Unable to locate package google-chrome-stable`

If you delete the project image and run `sail up`, is it installing without any errors?

**Comment by SerhiiCho** [comment]
I've changed the first line in `Dockerfile` to `FROM --platform=linux/amd64 ubuntu:22.04`, and the error `Unable to locate package google-chrome-stable` is gone. I saw in the Docker log that it was installing `google-chrome-stable` package 😅!

**Comment by Erol314** [comment]
> I wish I could help man 😞 I've tried to run Dusk with Sail but no luck on mac m1. The error was `Failed to connect to localhost port 9515 after 0 ms: Connection refused`


Next weekend i'll have a Mac with M2, I'll try to install the project without chrome and share results with you.

**Comment by vsergiu93** [comment]
@brendt I wanted to add more tests than just this ones, but this week I'll be out of town and I won't be able to work on this until next week, I think we can just review and merge it as it is.

**Pull request merged**
