### PR TITLE
User messages

### PR DESCRIPTION
**Pull request by brendt**
I'm considering first merging messages, so that we can use them in several places.

### CODE REVIEW

**Comment by brendt** [comment]
@SerhiiCho would you mind taking a look at what I'm working on here? Especially the `messages` page: http://rfc-vote.test/messages 

If you seed from fresh and login with the default admin account, you'll get 10 messages to play around with. Would appreciate any input :)

**Comment by SerhiiCho** [comment]
I see them:
image

What are these messages? What is the story behind them? How users are going to send them?

**Comment by brendt** [comment]
User's aren't going to send them directly. We'll use them as system notifications, for now. Two use cases I'm working on:

- comments on arguments, whenever a user comments on something you're watching, you'll receive a message
- when you get verified (or not)

Next step is to use these messages as the base to send out weekly digest mails, for people who have that setting enabled.

**Comment by brendt** [comment]
TODO: 
- [ ] add URL field in the message somewhere, since each message links to _something_ (could be a comment or argument, could be the user's profile, …)

**Comment by SerhiiCho** [comment]
> * add URL field in the message somewhere

let's me see

**Comment by SerhiiCho** [comment]
> * add URL field in the message somewhere

I've pushed [PR here](https://github.com/brendt/rfc-vote/pull/186), you can add a link inside the options popup now:

image

**Review by SerhiiCho — APPROVED** [review]
Looks great to me

**Pull request merged**
