### PR TITLE
Vote card redesign

### PR DESCRIPTION
**Pull request by SerhiiCho**
Changed the design of argument card on the voting page. The old design looks a bit bootstrapish.

## Vote up card before
image

## Vote up card after
image

## Vote down card before
image

## Vote down card after
image

## Other buttons before
image

## Other buttons after
image

## Two cards together before
image

## Two cards together after
image

I would love to continue some design improvements by small pull requests. I can further improve these argument cards in the future pull requests as well.

### CODE REVIEW

**Comment by brendt** [comment]
Looks great! 🤩

A couple of considerations: 

- if we're using an icon for removal, why not use one for editing as well?
- Personally though, I prefer to use text, as it's a bit more clear.
- The down arrow doesn't really work, since you're _upvoting_ an contra argument. I also don't want to convey that contra arguments are _bad_, a downwards arrow kind of has a negative feeling to it. I'm not sure how to fix it though 🤔

It's totally fine btw if you can't answer these questions or if you can't make any changes, I'm happy to merge this PR as-is, and work on it from there. Let me know!

**Comment by brendt** [comment]
Oh and, btw, you're more than welcome to send more of these kinds of PRs, really appreciate it!

**Comment by SerhiiCho** [comment]
Thanks, I agree with you. I'll make additional changes in a bit

**Comment by SerhiiCho** [comment]
Changed styles to a different version:

## Two arguments together without upvote
image

## Two arguments together with upvote of others arguments
image

## Editing argument
image

## Deleting argument
image

**Comment by SerhiiCho** [comment]
Let me know if you have other preferences and I will apply those

**Comment by SerhiiCho** [comment]
I will definitely want to change this prompt:
image

To make it as a tiny popup above the delete button to make it look nicer and position absolute, but I will make a separate PR for that.

**Comment by SerhiiCho** [comment]
If you don't like arrows, we can do something like this:

image

Where plus is upvoting the argument and minus is removing your vote from the argument

**Comment by brendt** [comment]
Of these examples, I think the arrows are the best. However I think we shouldn't rely on the vote counter alone to make a distinction between yes or no votes. I experimented with color and position (left and right), I think we could further explore that. But please don't take this as a critique — it's something I've been thinking about for the last days, but haven't found a proper solution for. It's surfacing now since this PR is making changes in this area, but it's not meant to say that the PR is bad — the opposite ;)

So let's say we merge in the arrow version (not sure if that's the one pushed to your branch?), and we'll work from there 👍

**Comment by SerhiiCho** [comment]
I resolved the conflict after the other PR was merge, wasn't a big deal. Yes, this branch is the arrow version:

image

**Comment by brendt** [comment]
Thanks a lot! Looks great :)

**Comment by brendt** [comment]
FYI, I made an issue for the yes/no problem :) https://github.com/brendt/rfc-vote/issues/67

**Comment by brendt** [comment]
Oh, and one more question: we'll need to fix the mobile design still. I can take care of it, just wanted to make sure you weren't already working on it :)

**Comment by SerhiiCho** [comment]
> Oh, and one more question: we'll need to fix the mobile design still. I can take care of it, just wanted to make sure you weren't already working on it :)

Great! I'm not working on anything right now. I've read the issue https://github.com/brendt/rfc-vote/issues/67 and it totally makes sense to me.

**Pull request merged**
