### PR TITLE
Comments styles

### PR DESCRIPTION
**Pull request by SerhiiCho**
Added styles for comments. There is a `comment-form.blade.php` with the comment form that needs to have the actual functionality. For now, it's just an empty form without action.

related #268 

image

### CODE REVIEW

**Comment by SerhiiCho** [comment]
The Qodana fail again, I have no idea what Qodana is

**Comment by vsergiu93** [comment]
It's a product by jetbrains, it's about code quality, I think there is a problem with the configuration, from the error it seems it does not have access to some secret `QODANA_TOKEN`. not sure if we can do much about it without @brendt.

**Comment by brendt** [comment]
FYI I've removed Qodana for now, I was trying some things out, but had to deal with sick kids yesterday, so it took a while to fix it :)

**Comment by brendt** [comment]
This looks great btw! Happy to merge it :)

**Pull request merged**
