### PR TITLE
show an indicator on the RFCs home page to show if the logged-in user has voted

### PR DESCRIPTION
**Pull request by MohammadAlhallaq**
This PR related to this [issue](https://github.com/brendt/rfc-vote/issues/108)

Screenshot 2023-08-18 at 9 26 33 PM

### CODE REVIEW

**Comment by brendt** [comment]
Important sidenote to make: if you're using `auth()->user`, you're retrieving a new User instance from the database. The downside is that that user doesn't have any relations loaded. That has the potential for slow performing queries. That's why it would be better to resolve the user in the controller, load the relations there (in this case it'd only be `user.argumentVotes`, and then use that user object. We already do this in the RfcDetailController:

```php
        $user = auth()->user();

        $user?->load([
            'arguments',
            'argumentVotes.argument',
            'viewedArguments',
        ]);
```

Would you mind changing the code to doing this? So that we don't run into potential performance issues.

**Comment by MohammadAlhallaq** [comment]
> Important sidenote to make: if you're using `auth()->user`, you're retrieving a new User instance from the database. The downside is that that user doesn't have any relations loaded. That has the potential for slow performing eager load issues. That's why it would be better to resolve the user in the controller, load the relations there (in this case it'd only be `user.argumentVotes`, and then use that user object. We already do this in the RfcDetailController:
> 
> ```
>         $user = auth()->user();
> 
>         $user?->load([
>             'arguments',
>             'argumentVotes.argument',
>             'viewedArguments',
>         ]);
> ```
> 
> Would you mind changing the code to doing this? So that we don't run into potential performance issues.


"You're totally right. Now, I think I've come up with an even better approach by making use of the RFC arguments. Since they are already loaded, I could match them with the logged-in user without the need to eager load more arguments for the user separately. What do you think of this?

**Comment by brendt** [comment]
Not sure I fully understand, but I'd say go for it and let me know when the code's ready :)

**Comment by MohammadAlhallaq** [comment]
I updated the PR.. you can now check the latest commit I've pushed..

**Comment by brendt** [comment]
Cool, thanks!

**Comment by SerhiiCho** [comment]
Closes #108

**Pull request merged**
