### PR TITLE
Feat/loadiing indicator

### PR DESCRIPTION
**Pull request by Kamleshpaul**
i added loading indicator for instant user feedback as `livewire` took some time to process 

Screenshot 2023-08-24 at 8 49 32 PM

i changes some of the places let me know if it is good or need to change anything else then i will change in all the places

### CODE REVIEW

**Comment by brendt** [comment]
Looks great! Did you want to merge this PR already, or should I wait?

**Comment by Kamleshpaul** [comment]
just wait for all the button

**Comment by brendt** [comment]
Ok, let me know when it's done :)

**Comment by Kamleshpaul** [comment]
> Ok, let me know when it's done :)

it is done you can merge now

**Pull request merged**
