### PR TITLE
Fix arguemnt of the day

### PR DESCRIPTION
**Pull request by MohammadAlhallaq**
This pull request addresses a bug where the raw query and the query builder were both including soft-deleted ArgumentVote records when counting the arguments of the day. To resolve this, I replaced them with Eloquent, which excludes soft-deleted records by default.,and eager loaded for the argument relation to eliminate the need for an extra query at the end.

apologies for the confusion, but I mistakenly pushed the changes to the previous PR without realizing that I was still on the same branch :/

### CODE REVIEW

**Comment by brendt** [comment]
Gotcha! Could you take a look at the merge conflict?

**Comment by MohammadAlhallaq** [comment]
done!

**Comment by SerhiiCho** [comment]
Wow! That's the pull request of the day for sure. Great catch

**Comment by brendt** [comment]
Thanks!

**Pull request merged**
