### PR TITLE
Viewed arguments style changes and Share argument buttons

### PR DESCRIPTION
**Pull request by SerhiiCho**
It should have been 2 PRs, but I messed up with GIT a bit, I hope it's not a complicated PR

## Viewed arguments
Instead of wrapping the whole argument with a blue border, maybe it's just better to make a small label in the right bottom corner:

image

When argument has not been seen, we just don't show it.

## Share argument on social media
I think it's a good idea to add the share on social media button to the argument card. It will be visible only when you hover over the argument card. Of course, since on the mobile version of the site we can't hover, so the social buttons will be visible on mobile.

image

For the link button, we can add JS where you click on it and the current URL is copied to your browser clipboard. It's better to do it in the separate commit.

We can also add more social icons in the future.

Moreover, I've added showing when argument was created to fill up the bottom-right corner a bit with some data.

## Argument card before changes
image

> I would do more tweaks to make it look better, just don't want this PR to grow more.

### CODE REVIEW

**Comment by brendt** [comment]
> When argument has not been seen, we just don't show it.

I think it's better to do it the other way around, mark it as "new", since those are the edge cases. I prefer as little text as possible for the majority of cards. Are you ok with changing that?

> For the link button, we can add JS where you click on it and the current URL is copied to your browser clipboard. It's better to do it in the separate commit.

Good idea, feel free to PR!

Btw, I think we're at the point where we need to consider a bigger overhaul of the argument cards. Two ideas I had:

- have a footer in each argument card that contains all "meta" info and actions, like username and vote, edited, all the buttons, … make it visually different from the content of the argument card (other bg, smaller font?)
- maybe have this footer only visible when hovering over a card? but that might be too big of a change

Do you want to give it a try?

**Comment by SerhiiCho** [comment]
> mark it as "new"

The keyword `new` is gonna be confusing, let's say the argument was published a month ago and user haven't seen it. People might think that `new` means that the argument was just published. Maybe it's better to use a different keyword?

What do you think about "Not seen"?

image

Or maybe you have other suggestion? If you want to use "new", we can do something like this:

image

Or do it without the word "argument" like this:

image

We can even animate it with tailwind utility `animate-pulse` to make it look like this:

Screen Recording 2023-08-17 at 13 24 51

**Comment by SerhiiCho** [comment]
I don't quite understand your suggestion about the argument footer, is it should be something like this?:

image

**Comment by SerhiiCho** [comment]
I would also remove user social links from the argument, it doesn't make sense to display user socials on his/her argument, to be honest. It's better to display them in the user profile.

**Comment by brendt** [comment]
> What do you think about "Not seen"?

Yeah I think that makes most sense :)

> animate-pulse

I'm not really a fan, but I'm not against it. 

> I don't quite understand your suggestion about the argument footer, is it should be something like this?:

Exactly 🤩 Although I would move the buttons to the footer as well and make them smaller, but up to you!

> Social links

Agree, let's remove them

There is _one_ more consideration about user reputation, but I'll make a separate issue for it, and you can pitch in if you want :) Let's first make sure we can merge this! Let me know when I can :)

**Comment by SerhiiCho** [comment]
> I'm not really a fan

so do I, I'll not use pulse

Okay, I'll make it work, it was just prototyping on screenshots

**Comment by SerhiiCho** [comment]
Here is the final result for now:
image

When you hover, social buttons appear:
image

I haven't touched the buttons yet, maybe it's better to make a separate PR. I think it's better to move buttons into a dropdown menu like this:
image

Unfortunately, you guys don't use Vue or React, I'm not very familiar with livewire.

**Comment by SerhiiCho** [comment]
I also removed edit at timestamp:
image

You can create a separate issue for this as well and we can place it somewhere

**Comment by brendt** [comment]
> I haven't touched the buttons yet, maybe it's better to make a separate PR. I think it's better to move buttons into a dropdown menu like this:

Sounds like a great idea :) 

> Since alpine is already in the project, I can make it work in alpine.js.

Cool 👍

> I also removed edit at timestamp:

That's ok for now, we might not need it.

Btw, thanks for all the quality PRs, really appreciate it!

**Comment by SerhiiCho** [comment]
> I haven't touched the buttons yet, maybe it's better to make a separate PR. I think it's better to move buttons into a dropdown menu like this:

Reference to PR https://github.com/brendt/rfc-vote/pull/137

**Pull request merged**
