### PR TITLE
Redesigned styles for the form that creates an argument

### PR DESCRIPTION
**Pull request by SerhiiCho**
Redesigned styles for the form that creates an argument:

## Before
image

## After
image

### CODE REVIEW

**Comment by vsergiu93** [comment]
@SerhiiCho look much better :).
Quick question, do you think we should remove this stats: `lines`, `words`, I mean the ones under the editor and above the save and cancel buttons?

**Comment by SerhiiCho** [comment]
@vsergiu93 since no one needs them, I would vote for removal of that line. Why would anyone care how many words they've typed

**Comment by brendt** [comment]
I agree, we should remove those. @vsergiu93 do you wanna take care of that since you PRd the editor? No worries if you can't do it :) If you want to, please submit a new PR after this one is merged :)

@SerhiiCho could you take a look at the merge conflict?

**Comment by SerhiiCho** [comment]
I also have a quick question: Do we care about translation functions or not? Some people (including me) use them and some don't.

In blade we have a @lang() function, and trans() & __() for everything else.

**Comment by brendt** [comment]
Since PHP internals is run in English, I don't think it makes sense putting in the effort for translations.

**Comment by vsergiu93** [comment]
@brendt I will take care of removing that line :)

**Pull request merged**
