### PR TITLE
🎨 Footer re-design

### PR DESCRIPTION
**Pull request by SerhiiCho**
I'm thinking to change a footer to something like this. Any suggestions? Maybe we can add something or make it look nicer? The license link may not exist as we don't yet have a license, and I don't like the icon for it.

We could also reflect links from the navigation bar to the footer as well.

## Light mode
image

## Dark mode
image

### CODE REVIEW

**Comment by brendt** [comment]
Nice!!

**Comment by brendt** [comment]
Don't really have any remarks myself

**Comment by SerhiiCho** [comment]
We can merge the footer as it is right now:

## Desktop version
image

## Mobile version
image

**Comment by brendt** [comment]
🔥

**Pull request merged**
