### PR TITLE
Dark mode 🌓

### PR DESCRIPTION
**Pull request by MohammadAlhallaq**
This pull request adds the dark theme styles to the messages page, while also considering the work that @SerhiiCho has already done to address the latest [issues](https://github.com/brendt/rfc-vote/pull/205) 👍🏻

Screenshot 2023-08-30 at 3 15 29 PM

### CODE REVIEW

**Comment by SerhiiCho** [comment]
Great! Btw, for these divide lines, we now have a tailwind utility `divider`. So you can do `divide-divider` or border-divider`

image

**Comment by SerhiiCho** [comment]
It will make them math to dark/light theme like this:
image

**Comment by SerhiiCho** [comment]
Thanks for dark them btw! I love it 😍

**Comment by MohammadAlhallaq** [comment]
> Great! Btw, for these divide lines, we now have a tailwind utility `divider`. So you can do `divide-divider` or `border-divider`
> 
> image

Thank You for the valuable feedback, especially since this was a wip. regarding the divider variable, yes, I noticed it and applied it to the admin RFCs pages and the verification requests page. However, it appears I might have overlooked it in this particular instance. I'll tackle it now 👍🏻

**Comment by brendt** [comment]
> Thanks for the dark theme btw! I love it 😍

@SerhiiCho please don't encourage others to use it… 😱

Joking aside, I really appreciate the work @MohammadAlhallaq has put into this. Thanks!

I'll go ahead and merge this one? Looks clean!

**Pull request merged**
