### PR TITLE
code highlighting on dark mode

### PR DESCRIPTION
**Pull request by MohammadAlhallaq**
This PR addresses the [issue](https://github.com/brendt/rfc-vote/issues/238) related to code highlighting in dark mode. Additionally, since the rendered code markdown was displaying different results from what I have locally, I would appreciate your feedback on the results if any errors were shown.

### CODE REVIEW

**Comment by MohammadAlhallaq** [comment]
> This increases compiled js significantly:
> 
> ## Before:
> image
> ## After:
> image

I've just committed a change that change the specified language to be highlighted using Highlight.js to include only one language, which will improve compilation time.

**Comment by MohammadAlhallaq** [comment]
> There are some issues with it. After editing argument and saving it looks like this: image
> 
> After page reload it changes: image
> 
> Light mode has dark background: image

This is really turning into something! Could you please provide me with the markdown used here?

**Comment by Plytas** [comment]
The bundle is a bit better:
image

---

This is the code I'm using:

\`\`\`php
echo 'Hello world';

function(string $foo): string {
	return $foo;
}
\`\`\`

**Comment by MohammadAlhallaq** [comment]
> The bundle is a bit better: image
> 
> This is the code I'm using:
> 
> ```php echo 'Hello world';
> 
> function(string $foo): string { return $foo; } ```


I have committed a few changes that should fix the background issue when the code is highlighted.

**Comment by MohammadAlhallaq** [comment]
> > There are some issues with it. After editing argument and saving it looks like this: image
> > After page reload it changes: image
> > Light mode has dark background: image
> 
> This is really turning into something! Could you please provide me with the markdown used here?

I have committed a few changes that should fix the background issue when the code is highlighted.

**Comment by brendt** [comment]
Looks nice! Let me know when it's ready to merge :)

**Comment by MohammadAlhallaq** [comment]
> Looks nice! Let me know when it's ready to merge :)

Have you tried it locally? For some reason, I'm not able to get the Markdown highlighting to work locally, even though it works fine for others. Just to make sure, it's producing the correct highlighting theme depending on the dark mode status

**Comment by brendt** [comment]
Screenshot 2023-09-06 at 10 32 42

Works well.

The contrast isn't all that great though, we'll probably need a different bg color

**Comment by brendt** [comment]
Nvm about the contrast, I had to run `npm i` :)

**Comment by brendt** [comment]
Screenshot 2023-09-06 at 10 34 06

Looks good :)

**Comment by brendt** [comment]
@MohammadAlhallaq can you fix the merge conflicts? After that we can merge it :)

**Comment by MohammadAlhallaq** [comment]
All set for merging 👍🏻

**Comment by brendt** [comment]
Thanks!

**Pull request merged**
