### PR TITLE
Feat add js to copy share link to clipboard

### PR DESCRIPTION
**Pull request by vsergiu93**
I hope this wasn't already taken care by someone else :)

### CODE REVIEW

**Comment by vsergiu93** [comment]
Ok, the tests are failing, but they seem to be unrelated to my change.

We either change the test db from sqllite to mysql or we try to use Eloquent for this query: 
```php
private function getArgumentOfTheDay(): ?Argument
    {
        $yesterday = now()->subDay()->endOfDay()->toDateTimeString();

        $argumentId = DB::select(<<<SQL
        SELECT argument_id, COUNT(*) as c, DATE_FORMAT(created_at, "%Y-%m-%d") as day
        FROM argument_votes
        WHERE created_at <= "$yesterday"
        GROUP BY argument_id, day
        ORDER BY day DESC, c DESC
        LIMIT 1
        SQL)[0]->argument_id;

        return Argument::find($argumentId);
    }
```
I think this is causing the tests to fail, and is in `app/Http/Controllers/HomeController.php`

**Comment by brendt** [comment]
Failing test has been fixed :)

**Comment by brendt** [comment]
Btw, I was testing this, but can't seem to get it to work locally? There's an error `Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')` in the console

Screenshot 2023-08-18 at 10 27 18

**Comment by vsergiu93** [comment]
Ah, yes forgot to mention, it only works on https or locahost. To test it locally on a url that is not localhost you need to do some things with your browser to treat insecure origins as secure.

Basically the clipboard api needs https or localhost to work.

**Comment by brendt** [comment]
Oooh ok, that makes sense!

**Pull request merged**
