### PR TITLE
Introduce larastan

### PR DESCRIPTION
**Pull request by Plytas**
I know there's already an existing PR #197, but it also includes ide-helper which is not really needed.

This PR introduces `larastan` at level 1 with minimal configuration and a minor change. According to [Laravel documentation](https://laravel.com/docs/10.x/eloquent-mutators#accessors-and-mutators) and [this post on laracasts](https://laracasts.com/discuss/channels/laravel/l9-attribute-not-recognized-by-larastan?page=1&replyId=823471) model attributes should be protected methods and we can specify their return type using generics.

### CODE REVIEW

**Comment by brendt** [comment]
@Erol314 wanna sync up on this? I'm more inclined to merge the simpler PR at this moment

**Comment by brendt** [comment]
What I'm missing in both PRs is the github CI action btw, you can probably copy it from another repo of mine, with minor adjustments: https://github.com/brendt/tempest/blob/main/.github/workflows/phpstan.yml

**Comment by Plytas** [comment]
@brendt looks like tempest is closed source or the link is wrong.
I added a workflow with caching. Can you ping me once it runs so we can see if it worked or not?

**Comment by brendt** [comment]
Oh, my bad 😅 I'm running it now :)

**Comment by Plytas** [comment]
@brendt fixed (hopefully) phpstan CI cache path so workflow should pass now.

**Comment by brendt** [comment]
Awesome! Btw: make sure to add yourself in [contributors.json](https://github.com/brendt/rfc-vote/blob/main/contributors.json), so you'll get listed on the website as well :)

**Pull request merged**
